command_upcase = "ignore"          # "lowcase", "upcase"
enable_external_cmake_lint = false # true to use external cmake-lint
line_max_words = 100               # internal lint just supports longest check
